// This file is generated by a script, do not edit it directly.

export const FILE_TRANSFER_LANG = {LANG0:{"code":"7DdGwY94ZJJQP49c","desc":"普通话"},LANG1:{"code":"GkdNk61UG4Z5YUAi","desc":"英语"},LANG2:{"code":"geNIOyz0nIsgGENB","desc":"中英混合"}};
export const FILE_TRANSFER_STATUS = {INIT:{"code":"I","desc":"初始"},SUBTITLE_INIT:{"code":"SI","desc":"待生成字幕"},SUBTITLE_PENDING:{"code":"SP","desc":"生成字幕中"},SUBTITLE_SUCCESS:{"code":"SS","desc":"生成字幕成功"},SUBTITLE_FAILURE:{"code":"SF","desc":"生成字幕失败"},DELETED:{"code":"D","desc":"失效"}};
export const FILE_TRANSFER_PAY_STATUS = {I:{"code":"I","desc":"未支付"},P:{"code":"P","desc":"处理中"},S:{"code":"S","desc":"支付成功"},F:{"code":"F","desc":"支付失败"}};

export const FILE_TRANSFER_LANG_ARRAY = [{"code":"7DdGwY94ZJJQP49c","desc":"普通话"},{"code":"GkdNk61UG4Z5YUAi","desc":"英语"},{"code":"geNIOyz0nIsgGENB","desc":"中英混合"}];
export const FILE_TRANSFER_STATUS_ARRAY = [{"code":"I","desc":"初始"},{"code":"SI","desc":"待生成字幕"},{"code":"SP","desc":"生成字幕中"},{"code":"SS","desc":"生成字幕成功"},{"code":"SF","desc":"生成字幕失败"},{"code":"D","desc":"失效"}];
export const FILE_TRANSFER_PAY_STATUS_ARRAY = [{"code":"I","desc":"未支付"},{"code":"P","desc":"处理中"},{"code":"S","desc":"支付成功"},{"code":"F","desc":"支付失败"}];
