# 用户注册
POST http://localhost:18000/nls/web/member/register
Content-Type: application/json

{
  "mobile": "12345678903",
  "password": "1123",
  "code": "654654"
}

###

# 手机号已注册
POST http://localhost:18000/nls/web/member/register
Content-Type: application/json

{
  "mobile": "12345678903",
  "password": "3211",
  "code": "456456"
}

###

# 手机号注册校验通过
POST http://localhost:18000/nls/web/member/register
Content-Type: application/json

{
  "mobile": "12345678904",
  "password": "3211",
  "code": "456456"
}

###

# 发送生成的验证码
POST http://localhost:18000/nls/web/member/register
Content-Type: application/json

{
  "mobile": "12345678906",
  "password": "3211",
  "code": "035920"
}

###

# 登录
POST http://localhost:18000/nls/web/member/login
Content-Type: application/json

{
  "mobile": "12345678908",
  "password": "",
  "imageCode": "",
  "imageCodeToken": ""
}

###

# 测试登录, 并设置全局token
POST http://localhost:18000/nls/web/member/login
Content-Type: application/json

{
  "mobile": "12345678908",
  "password": "$2b$10$ltWxALzJw.UM46trElkkKOnSrRtym0.VMSD8.mWWRdASZdJSQs4rm",
  "imageCode": "na3y",
  "imageCodeToken": "123"
}

> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.content.token));
    client.global.set("token", response.body.content.token);
%}

###