POST http://localhost:18000/nls/web/vod/get-upload-auth
Content-Type: application/json

{
  "name": "test-0621.mp4",
  "key": "2025062101"
}

###

GET http://localhost:18000/nls/web/vod/calc-amount/40147b7e510f71f0bfcf4531959c0102
Accept: application/json

###